/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Feedback extends javax.swing.JFrame {

   String userID;
   Connection con;
    PreparedStatement st,st1;
    ResultSet rs;
    public Feedback() {
        initComponents();
    }
    public Feedback(String fid)
    {
        userID=fid;
        try
        {
            
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/assignment2","root","");
            st=con.prepareStatement("select  u_name from usertb where u_id=?");
            st.setString(1,userID);
            rs=st.executeQuery();
            if(rs.next())
            {
                String unm = rs.getString("u_name");
                initComponents();
                username_lbl.setText("Hello "+unm+",");
            }    
            else
            {
                JOptionPane.showMessageDialog(null,"An error occured!!");
            }
            
            }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(null,"Failed");   
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        feedback_bg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        excellent_rb = new javax.swing.JRadioButton();
        vgood_rb = new javax.swing.JRadioButton();
        good_rb = new javax.swing.JRadioButton();
        avg_rb = new javax.swing.JRadioButton();
        poor_rb = new javax.swing.JRadioButton();
        submit_fb_btn = new javax.swing.JButton();
        username_lbl = new javax.swing.JLabel();
        ViewFeedback_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FEEDBACK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Please provide your valuable feedback,");

        feedback_bg.add(excellent_rb);
        excellent_rb.setText("Excellent");

        feedback_bg.add(vgood_rb);
        vgood_rb.setText("Very Good");

        feedback_bg.add(good_rb);
        good_rb.setText("Good");

        feedback_bg.add(avg_rb);
        avg_rb.setText("Average");

        feedback_bg.add(poor_rb);
        poor_rb.setText("Poor");

        submit_fb_btn.setBackground(new java.awt.Color(0, 0, 0));
        submit_fb_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit_fb_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_fb_btn.setText("Submit");
        submit_fb_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_fb_btnActionPerformed(evt);
            }
        });

        username_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        ViewFeedback_btn.setBackground(new java.awt.Color(0, 0, 0));
        ViewFeedback_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ViewFeedback_btn.setForeground(new java.awt.Color(255, 255, 255));
        ViewFeedback_btn.setText("View Feedback");
        ViewFeedback_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewFeedback_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(username_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poor_rb)
                            .addComponent(avg_rb)
                            .addComponent(good_rb)
                            .addComponent(vgood_rb)
                            .addComponent(excellent_rb))
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submit_fb_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(ViewFeedback_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(username_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(excellent_rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vgood_rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(good_rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avg_rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poor_rb)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_fb_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewFeedback_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_fb_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_fb_btnActionPerformed
       String feedback=null;
       if(excellent_rb.isSelected())
       {
           feedback="Excellent";
       }
       else if(vgood_rb.isSelected())
       {
           feedback="Very Good";
       }
       else if(good_rb.isSelected())
       {
           feedback="Good";
       }
       else if(avg_rb.isSelected())
       {
           feedback="Average";
       }
       else if(poor_rb.isSelected())
       {
           feedback="Poor";
       }
       else       
       {
           JOptionPane.showMessageDialog(null,"Choose an option!!");
           return;
       }
        try
           {
               
              con=DriverManager.getConnection("jdbc:mysql://localhost:3306/assignment2","root","");
              st=con.prepareStatement("insert into feedbacktb (u_id,f_message,f_datetime,f_flagbit) values((select u_id from usertb where u_id=?),?,CURRENT_TIMESTAMP,0)"); 
              st.setString(1,userID);
              st.setString(2,feedback);
              st.executeUpdate();
              con.close();
              JOptionPane.showMessageDialog(null,"Thank you for your feedback");
           }
           catch(Exception e)
           {
                e.printStackTrace();
               JOptionPane.showMessageDialog(null,"Failed");
           }
       
    }//GEN-LAST:event_submit_fb_btnActionPerformed

    private void ViewFeedback_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewFeedback_btnActionPerformed
        ViewFeedback vfb=new ViewFeedback(userID);
        vfb.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_ViewFeedback_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewFeedback_btn;
    private javax.swing.JRadioButton avg_rb;
    private javax.swing.JRadioButton excellent_rb;
    private javax.swing.ButtonGroup feedback_bg;
    private javax.swing.JRadioButton good_rb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton poor_rb;
    private javax.swing.JButton submit_fb_btn;
    private javax.swing.JLabel username_lbl;
    private javax.swing.JRadioButton vgood_rb;
    // End of variables declaration//GEN-END:variables
}
